### ISSUE TITLE
Where do firewall.rules come from?

### ISSUE THREAD

**Issue by danbst** [kampfschlaefer/nixconfig#1]
https://github.com/kampfschlaefer/nixconfig/blob/202429247016e26f200bbecb358f73da7a64b785/portal/containers/firewall.nix#L55

Where is `networking.firewall.rules` option defined? It is not part of standart Nixos

**Comment by kampfschlaefer** [comment]
Nope, that is part of https://github.com/NixOS/nixpkgs/pull/12940 which I test-drive on my personal nixpkgs copy ;-)

**Comment by danbst** [comment]
Nice. It's more verbose then iptables syntax, but is an improvement for merging.
