### ISSUE TITLE
Why is it useful to start sshd on demand?

### ISSUE THREAD

**Issue by danbst** [kampfschlaefer/nixconfig#2]
https://github.com/kampfschlaefer/nixconfig/blob/202429247016e26f200bbecb358f73da7a64b785/portal/containers/imap.nix#L57

Why is it useful to start sshd on demand? Can't you get in trouble with this?

**Comment by kampfschlaefer** [comment]
In this container I am not yet sure whether I need the sshd at all. So I don't want it running and taking resources when its not needed. For example on the mpd-container I need ssh only when copying new music via scp, all other maintainance like restarting mpd is done with `nixos-container run mpd -- systemctl restart mpd`.

**Comment by danbst** [comment]
Ah, didn't notice that you use it only for containers.
