### ISSUE TITLE
Extensive use of lib.mkOverride

### ISSUE THREAD

**Issue by danbst** [kampfschlaefer/nixconfig#3]
For example,

https://github.com/kampfschlaefer/nixconfig/blob/202429247016e26f200bbecb358f73da7a64b785/portal/default.nix#L77

You use custom priority 100. What is the logic behind this and many other `lib.mkOverride 100` throughout your nixconfig?

**Comment by kampfschlaefer** [comment]
I need to override some of these values for the tests in test-portal.nix. Without lib.mkOverride they wouldn't be override-able in the first place. At least not that I know of.

**Comment by danbst** [comment]
Hm. Looking at https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix#L455
```
mkOptionDefault = mkOverride 1001; # priority of option defaults
```
So all options must be overridable by default with priority 1001. Even `mkForce` is overridable (priority 50)

**Comment by kampfschlaefer** [comment]
Sadly options like 'networking.hostName' are not defined as mkOptionDefault, but only as mkOption. So without the usage of mkOverride, the tests in test-portal.nix fail to even compile.
